Updating names & PBI 34
DevOpsThoughts/E-Commerce pull request #1
Opened 2017-05-29 13:41 UTC by mabdelalim

2017-05-29 14:59 UTC, MohamedRadwan-DevOps requested changes
Only names, I don't approve the PBI 34 as it contains many format and I only need simple html, btw, looking at some old PBIs you did, they should not include all these format as HTML so this needs to be fixed later

2017-05-30 15:26 UTC, mabdelalim commented
changes applied to the recent commit, Please check it.

2017-05-30 23:06 UTC, MohamedRadwan-DevOps requested changes
Rejected, I only need one pull request for names...but you add more...
I want only names

2017-05-30 23:09 UTC, MohamedRadwan-DevOps requested changes
Divide your work for many request

2017-05-31 15:25 UTC, MohamedRadwan-DevOps approved these changes

2017-06-01 00:46 UTC, MohamedRadwan-DevOps requested changes
Approved by mistake

2017-06-01 00:46 UTC, closed without merging